services:
  zf-ros2-driver:
    image: zf-ros2-driver
    build:
      context: .
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - ROS_DOMAIN_ID=0
    network_mode: host
    entrypoint: "sleep infinity"
#    command: ros2 launch frgen21_ros2 frgen21_default.launch.py
